from turtle import*
color("red")
bgcolor("black")
begin_fill()
pensize(3)
left(50)
forward(133)
circle(50,200)
right(140)
circle(50,200)
forward(133)
end_fill()
color("pink")
write("            garmadon.dev",font=("verdana",7,"bold"))
exitonclick()